# Generated by Django 4.2.27 on 2025-12-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='questions',
        ),
        migrations.AlterField(
            model_name='rule',
            name='distribution_strategy',
            field=models.CharField(choices=[('singleChoice', 'singleChoice'), ('multiSelect', 'multiSelect'), ('trueFalse', 'trueFalse')], max_length=20),
        ),
        migrations.CreateModel(
            name='BatteryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('singleChoice', 'singleChoice'), ('multiSelect', 'multiSelect'), ('trueFalse', 'trueFalse')], max_length=20)),
                ('question', models.TextField()),
                ('explanation', models.TextField(blank=True, default='')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_rel', to='api.battery')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_questions', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.batteryquestion')),
            ],
        ),
    ]
