# Generated by Django 4.2.27 on 2026-01-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
