# Generated by Codex on 2026-02-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_emailverification"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT
      conrelid::regclass AS table_name,
      conname AS constraint_name,
      pg_get_constraintdef(c.oid) AS definition
    FROM pg_constraint c
    WHERE contype = 'f'
      AND confrelid = 'api_user'::regclass
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I;', r.table_name, r.constraint_name);
    EXECUTE format(
      'ALTER TABLE %s ADD CONSTRAINT %I %s ON DELETE CASCADE;',
      r.table_name,
      r.constraint_name,
      regexp_replace(r.definition, ' ON DELETE [A-Z ]+', '')
    );
  END LOOP;
END$$;
""",
            reverse_sql=migrations.RunSQL.noop,
        )
    ]

