# Generated by Django 4.2.27 on 2025-12-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_battery_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('finished', 'finished'), ('abandoned', 'abandoned')], default='in_progress', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.battery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.batteryattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='api.batteryquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_single_attempts', to='api.batteryoption')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_multi_attempts', to='api.batteryoption')),
            ],
        ),
    ]
