# Generated by Django 4.2.27 on 2025-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_batteryattempt_batteryattemptanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_documents',
        ),
        migrations.AddField(
            model_name='topic',
            name='related_sections',
            field=models.ManyToManyField(blank=True, related_name='topics', to='api.section'),
        ),
    ]
