# Generated by Django 4.2.27 on 2026-01-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
    ]
