# Generated by Django 4.2.27 on 2026-01-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
