# Generated by Django 4.2.27 on 2025-12-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_topic_related_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='distribution_strategy',
            field=models.CharField(choices=[('singleChoice', 'singleChoice'), ('multiSelect', 'multiSelect'), ('trueFalse', 'trueFalse'), ('mixed', 'mixed')], max_length=20),
        ),
    ]
