# Generated by Django 4.2.27 on 2026-01-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
    ]
