# Generated by Django 4.2.27 on 2026-01-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qapair',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='qapair',
            constraint=models.UniqueConstraint(fields=('document', 'qa_index', 'job_id'), name='uniq_qapairs_document_qaindex_jobid'),
        ),
    ]
