# Generated by Codex on 2026-02-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_fk_cascade"),
        ("api", "0007_authtoken_token_cascade"),
    ]

    operations = []

