# Generated by Django 4.2.27 on 2026-01-02 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_qapair_deck_permission_plan_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='api.project'),
        ),
        migrations.AddField(
            model_name='deck',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='decks', to='api.section'),
        ),
    ]
