# Generated by Django 4.2.27 on 2026-01-16 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('job_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('time_to_answer_ms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.flashcard')),
            ],
            options={
                'db_table': 'api_flashcardreview',
            },
        ),
    ]
