# Generated by Codex on 2026-02-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_merge_0003_user_fk_cascade_0007_authtoken_token_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_invites",
                to="api.user",
            ),
        ),
    ]
