# Generated by Django 4.2.27 on 2026-01-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deck_description_deck_project_deck_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='external_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
