# Generated by Django 4.2.27 on 2026-01-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flashcardreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='summary_document', to='api.document')),
            ],
            options={
                'db_table': 'summary_document',
            },
        ),
    ]
