# Generated by Django 4.2.27 on 2026-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_summarydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('project', 'hash'), name='uniq_document_project_hash'),
        ),
    ]
