# Generated by Django 4.2.27 on 2026-02-08 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_document_uploaded_by_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='key',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Use only letters, numbers, underscores, hyphens, or dots.', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
    ]
