# Generated by Django 4.2.27 on 2026-01-11 03:06

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qapair',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=api.models.document_upload_to),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('question_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'db_table': 'chunks',
                'managed': True,
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
