# Generated by Django 4.2.27 on 2026-02-09 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_resource_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUploadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('document_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('rejected', 'Rejected')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_events', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_upload_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_upload_events',
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='document_up_user_id_b5978a_idx')],
            },
        ),
    ]
