# Generated by Django 4.2.27 on 2026-01-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_qapair_options_and_more'),
        ('api', 'fix'),
    ]

    operations = [
    ]
