# Generated by Django 4.2.27 on 2026-02-11 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_qapair_meta_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(choices=[('battery', 'Battery'), ('deck', 'Deck')], max_length=20)),
                ('requested_access', models.CharField(choices=[('view', 'View Only'), ('copy', 'View + Copy'), ('edit', 'Edit')], default='view', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.battery')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.deck')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(fields=('battery', 'requester'), name='uniq_accessreq_battery_requester'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(fields=('deck', 'requester'), name='uniq_accessreq_deck_requester'),
        ),
    ]
