# Generated by Django 4.2.27 on 2026-02-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_battery_description_accessrequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
