# Generated by Django 4.2.27 on 2026-02-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_battery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-id']},
        ),
    ]
