# Generated by Django 4.2.27 on 2026-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_qapair_require_index'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE IF EXISTS api_section DROP COLUMN IF EXISTS external_document_id;",
                    reverse_sql="",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='section',
                    name='external_document_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='qapair',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='qapair',
            unique_together={('document', 'qa_index')},
        ),
    ]
