# Generated by Django 4.2.27 on 2026-02-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_rule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='summary_jobs',
                        to='api.document',
                    ),
                ),
            ],
            options={
                'db_table': 'summary_job',
            },
        ),
        migrations.AddConstraint(
            model_name='summaryjob',
            constraint=models.UniqueConstraint(
                fields=('job_id', 'item_type'),
                name='uix_summary_job_type',
            ),
        ),
    ]

