# Generated by Django 4.2.27 on 2026-02-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_summaryjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
