# Generated by Django 4.2.27 on 2026-02-19 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_topic_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic'),
        ),
    ]
