# Generated by Django 4.2.27 on 2026-02-22 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deck_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
    ]
