# Generated by Django 4.2.27 on 2026-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='batteries', to='api.section'),
        ),
    ]
