# Generated by Django 4.2.27 on 2026-01-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_conversationmessage_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
