# Generated by Codex on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_notification_center"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS notifications CASCADE;
            CREATE TABLE notifications (
                id BIGSERIAL PRIMARY KEY,
                key VARCHAR(80) NOT NULL,
                title VARCHAR(200) NOT NULL,
                body TEXT NOT NULL DEFAULT '',
                level VARCHAR(20) NOT NULL DEFAULT 'info',
                data JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS notifications_key_created_at_idx
                ON notifications (key, created_at);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS notifications CASCADE;
            """,
        ),
    ]
