# Generated by Django 4.2.27 on 2026-03-14 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDecryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('secret', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_decryption_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_decryption_keys',
            },
        ),
    ]
