# Generated by Django 4.2.27 on 2026-03-14 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pdfdecryptionkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdecryptionkey',
            name='pdf_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdecryptionkey',
            name='pdf_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pdfdecryptionkey',
            name='resource_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdecryptionkey',
            name='resource_kind',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='pdfdecryptionkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_decryption_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pdfdecryptionkey',
            index=models.Index(fields=['user', 'created_at'], name='pdf_decrypt_user_id_b5ea89_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdecryptionkey',
            index=models.Index(fields=['user', 'pdf_hash'], name='pdf_decrypt_user_id_ff648d_idx'),
        ),
    ]
