# Generated by Django 4.2.27 on 2026-03-14 01:41

from django.db import migrations


def _rename_index_if_needed(old_name, new_name):
    return f"""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'i' AND relname = '{old_name}')
       AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'i' AND relname = '{new_name}') THEN
        EXECUTE 'ALTER INDEX {old_name} RENAME TO {new_name}';
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_notificatio_key_1d38d4_idx_notificatio_key_b9d77c_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_rename_index_if_needed(
                        'notificatio_key_1d38d4_idx',
                        'notificatio_key_b9d77c_idx',
                    ),
                    reverse_sql=_rename_index_if_needed(
                        'notificatio_key_b9d77c_idx',
                        'notificatio_key_1d38d4_idx',
                    ),
                ),
                migrations.RunSQL(
                    sql=_rename_index_if_needed(
                        'plan_usage_c_user_id_6a0d40_idx',
                        'plan_usage__user_id_747633_idx',
                    ),
                    reverse_sql=_rename_index_if_needed(
                        'plan_usage__user_id_747633_idx',
                        'plan_usage_c_user_id_6a0d40_idx',
                    ),
                ),
                migrations.RunSQL(
                    sql=_rename_index_if_needed(
                        'user_notif_user_id_87c8e3_idx',
                        'user_notifi_user_id_94ad44_idx',
                    ),
                    reverse_sql=_rename_index_if_needed(
                        'user_notifi_user_id_94ad44_idx',
                        'user_notif_user_id_87c8e3_idx',
                    ),
                ),
                migrations.RunSQL(
                    sql=_rename_index_if_needed(
                        'user_notif_user_id_9b1a90_idx',
                        'user_notifi_user_id_01932b_idx',
                    ),
                    reverse_sql=_rename_index_if_needed(
                        'user_notifi_user_id_01932b_idx',
                        'user_notif_user_id_9b1a90_idx',
                    ),
                ),
                migrations.RunSQL(
                    sql=_rename_index_if_needed(
                        'user_notif_user_id_4b6a3c_idx',
                        'user_notifi_user_id_c5f7fb_idx',
                    ),
                    reverse_sql=_rename_index_if_needed(
                        'user_notifi_user_id_c5f7fb_idx',
                        'user_notif_user_id_4b6a3c_idx',
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_key_b9d77c_idx',
                    old_name='notificatio_key_1d38d4_idx',
                ),
                migrations.RenameIndex(
                    model_name='planusagecounter',
                    new_name='plan_usage__user_id_747633_idx',
                    old_name='plan_usage_c_user_id_6a0d40_idx',
                ),
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='user_notifi_user_id_94ad44_idx',
                    old_name='user_notif_user_id_87c8e3_idx',
                ),
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='user_notifi_user_id_01932b_idx',
                    old_name='user_notif_user_id_9b1a90_idx',
                ),
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='user_notifi_user_id_c5f7fb_idx',
                    old_name='user_notif_user_id_4b6a3c_idx',
                ),
            ],
        ),
    ]
