# Generated by Django 4.2.27 on 2026-03-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_document_type'),
        ('api', '0033_flashcard_back_image_was_optimized_db_default'),
    ]

    operations = [
    ]
