# Generated by Django 4.2.27 on 2026-06-25 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20260317_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprise_business_units',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('aviation', 'Aviation'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics'), ('technology', 'Technology'), ('finance', 'Finance'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('company_size', models.CharField(blank=True, choices=[('1_10', '1-10'), ('11_50', '11-50'), ('51_200', '51-200'), ('201_500', '201-500'), ('501_1000', '501-1,000'), ('1000_plus', '1,000+')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'enterprise_companies',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='api.businessunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_team_memberships',
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('flashcard_review', 'Flashcard Review'), ('battery_completed', 'Battery Completed'), ('battery_attempted', 'Battery Attempted'), ('module_completed', 'Module Completed'), ('module_started', 'Module Started'), ('learning_path_completed', 'Learning Path Completed'), ('learning_path_assigned', 'Learning Path Assigned'), ('review_completed', 'Review Completed'), ('compliance_completed', 'Compliance Completed'), ('compliance_assigned', 'Compliance Assigned'), ('compliance_expired', 'Compliance Expired'), ('certificate_issued', 'Certificate Issued'), ('certificate_expired', 'Certificate Expired'), ('certificate_revoked', 'Certificate Revoked'), ('employee_activated', 'Employee Activated'), ('knowledge_gap_detected', 'Knowledge Gap Detected'), ('document_uploaded', 'Document Uploaded'), ('document_processed', 'Document Processed'), ('training_generated', 'Training Generated'), ('training_regenerated', 'Training Regenerated'), ('retention_recalculated', 'Retention Recalculated')], db_index=True, max_length=60)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='api.battery')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='api.company')),
                ('flashcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='api.flashcard')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_learning_events',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('global_retention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('global_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('onboarding_completion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employees_at_risk', models.PositiveIntegerField(default=0)),
                ('employees_in_onboarding', models.PositiveIntegerField(default=0)),
                ('active_employees', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='api.company')),
            ],
            options={
                'db_table': 'enterprise_knowledge_health_snapshots',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('employee_code', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], max_length=30)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_profile_users', to='api.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('trainer', 'Trainer'), ('employee', 'Employee'), ('auditor', 'Auditor')], default='employee', max_length=20)),
                ('employee_stage', models.CharField(choices=[('candidate', 'Candidate'), ('onboarding', 'Onboarding'), ('trainee', 'Trainee'), ('active_employee', 'Active Employee'), ('contractor', 'Contractor'), ('former_employee', 'Former Employee')], default='onboarding', max_length=30)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('stage_changed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_company_invites', to=settings.AUTH_USER_MODEL)),
                ('stage_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_stage_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_company_memberships',
            },
        ),
        migrations.AddField(
            model_name='businessunit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_business_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_membership_team_user'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['company'], name='enterprise__company_836fad_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['business_unit'], name='enterprise__busines_764942_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['manager'], name='enterprise__manager_562c87_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_team_company_name'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['company'], name='enterprise__company_2d10b0_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user'], name='enterprise__user_id_f0c077_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['event_type'], name='enterprise__event_t_c4383b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['created_at'], name='enterprise__created_868a37_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['company', 'user'], name='enterprise__company_abd3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['company', 'event_type'], name='enterprise__company_9338cb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['company', 'created_at'], name='enterprise__company_0f81c7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgehealthsnapshot',
            index=models.Index(fields=['company', 'snapshot_date'], name='enterprise__company_ddd4a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgehealthsnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'snapshot_date'), name='uniq_health_snapshot_company_date'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company'], name='enterprise__company_903ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user'], name='enterprise__user_id_615cea_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['role'], name='enterprise__role_c8c485_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['employee_stage'], name='enterprise__employe_a6aeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['status'], name='enterprise__status_687f76_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_a3427f_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'role'], name='enterprise__company_fbe8ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_membership_company_user'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='enterprise__slug_27e802_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='enterprise__owner_i_9f9c95_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='enterprise__is_acti_893086_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_bu_company_code'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_bu_company_name'),
        ),
    ]
