# Generated by Django 4.2.27 on 2026-06-25 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_enterprise_phase1_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enterprise_learning_modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_paths', to='api.businessunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_paths', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_learning_paths', to='api.project')),
            ],
            options={
                'db_table': 'enterprise_learning_paths',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='api.businessunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_training_programs',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_program_versions', to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_versions', to='api.learningpath')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.trainingprogram')),
            ],
            options={
                'db_table': 'enterprise_training_program_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_learning_paths', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to='api.company')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.learningpath')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to='api.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_learning_path_assignments',
            },
        ),
        migrations.CreateModel(
            name='LearningModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='api.learningpathassignment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='api.learningmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_learning_module_progresses',
            },
        ),
        migrations.CreateModel(
            name='LearningModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('topic', 'Topic'), ('battery', 'Battery / Quiz'), ('deck', 'Flashcard Deck'), ('document', 'Document')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_items', to='api.battery')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_items', to='api.deck')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_items', to='api.document')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.learningmodule')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_items', to='api.topic')),
            ],
            options={
                'db_table': 'enterprise_learning_module_items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.learningpath'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='learning_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.learningmodule'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.learningpath'),
        ),
        migrations.AddConstraint(
            model_name='trainingprogramversion',
            constraint=models.UniqueConstraint(fields=('program', 'version_number'), name='uniq_training_program_version_number'),
        ),
        migrations.AddIndex(
            model_name='trainingprogram',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_9e5206_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathassignment',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_e9e0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathassignment',
            index=models.Index(fields=['user', 'status'], name='enterprise__user_id_19704d_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathassignment',
            index=models.Index(fields=['team', 'status'], name='enterprise__team_id_33cc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathassignment',
            index=models.Index(fields=['due_date'], name='enterprise__due_dat_0b3565_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpathassignment',
            index=models.Index(fields=['company', 'due_date'], name='enterprise__company_cdd751_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_ec9047_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['company', 'created_at'], name='enterprise__company_3d3376_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmoduleprogress',
            index=models.Index(fields=['user', 'status'], name='enterprise__user_id_919294_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmoduleprogress',
            index=models.Index(fields=['assignment', 'status'], name='enterprise__assignm_f9e911_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmoduleprogress',
            index=models.Index(fields=['assignment', 'user'], name='enterprise__assignm_498693_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningmoduleprogress',
            constraint=models.UniqueConstraint(fields=('assignment', 'module', 'user'), name='uniq_module_progress_assignment_module_user'),
        ),
        migrations.AddIndex(
            model_name='learningmodule',
            index=models.Index(fields=['learning_path', 'order'], name='enterprise__learnin_42bc58_idx'),
        ),
    ]
