# Generated by Django 4.2.27 on 2026-06-25 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_enterprise_phase2_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('flashcard', 'Flashcard Review'), ('battery', 'Battery / Quiz'), ('reading', 'Reading / Study'), ('assessment', 'Assessment')], default='battery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score after completion (0-100)', max_digits=6, null=True)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, help_text='SM-2 ease factor (1.3 – 2.5)', max_digits=4)),
                ('interval_days', models.PositiveIntegerField(default=1, help_text='Days until next review')),
                ('repetition_count', models.PositiveIntegerField(default=0, help_text='How many times this item has been reviewed')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='api.battery')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to='api.company')),
                ('flashcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='api.flashcard')),
                ('learning_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='api.learningmodule')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='api.learningpath')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_review_schedules',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['company', 'user', 'due_date'], name='enterprise__company_3b5f34_idx'), models.Index(fields=['user', 'status'], name='enterprise__user_id_0d9642_idx'), models.Index(fields=['user', 'due_date'], name='enterprise__user_id_690c38_idx'), models.Index(fields=['company', 'status'], name='enterprise__company_e72d62_idx'), models.Index(fields=['due_date'], name='enterprise__due_dat_854d68_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetentionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('retention_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('assessment_count', models.PositiveIntegerField(default=0)),
                ('last_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_snapshots', to='api.company')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_snapshots', to='api.learningpath')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_snapshots', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_retention_snapshots',
                'ordering': ['-snapshot_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'user'], name='enterprise__company_4776da_idx'), models.Index(fields=['company', 'snapshot_date'], name='enterprise__company_a99f79_idx'), models.Index(fields=['user', 'topic'], name='enterprise__user_id_910599_idx'), models.Index(fields=['user', 'learning_path'], name='enterprise__user_id_795c5d_idx'), models.Index(fields=['company', 'user', 'snapshot_date'], name='enterprise__company_cbe469_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('retention_score_at_detection', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_gaps', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gaps', to='api.company')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='api.learningpath')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gaps', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='api.team')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gaps', to='api.topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_knowledge_gaps',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='enterprise__company_d210cb_idx'), models.Index(fields=['company', 'severity'], name='enterprise__company_887ed2_idx'), models.Index(fields=['user', 'status'], name='enterprise__user_id_b14402_idx'), models.Index(fields=['team', 'status'], name='enterprise__team_id_d90751_idx'), models.Index(fields=['company', 'user', 'status'], name='enterprise__company_189717_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('battery', 'Battery / Quiz'), ('flashcard_session', 'Flashcard Session'), ('review', 'Scheduled Review'), ('manual', 'Manual Assessment')], default='battery', max_length=30)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_correct', models.PositiveIntegerField(default=0)),
                ('retention_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 retention score at the time of this assessment', max_digits=6)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 confidence based on score consistency', max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments', to='api.battery')),
                ('battery_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments', to='api.batteryattempt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_assessments', to='api.company')),
                ('learning_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments', to='api.learningmodule')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments', to='api.learningpath')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments', to='api.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_knowledge_assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'user'], name='enterprise__company_9a1104_idx'), models.Index(fields=['company', 'created_at'], name='enterprise__company_49d715_idx'), models.Index(fields=['user', 'topic'], name='enterprise__user_id_581473_idx'), models.Index(fields=['user', 'battery'], name='enterprise__user_id_c7b695_idx'), models.Index(fields=['company', 'user', 'created_at'], name='enterprise__company_663a6a_idx')],
            },
        ),
    ]
