# Generated by Django 4.2.27 on 2026-06-25 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_enterprise_phase3_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique code within the company', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('compliance_type', models.CharField(choices=[('regulatory', 'Regulatory'), ('internal', 'Internal Policy'), ('certification', 'Certification'), ('safety', 'Safety'), ('other', 'Other')], default='regulatory', max_length=30)),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Bi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='annual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Days the compliance remains valid after completion')),
                ('requires_score', models.BooleanField(default=False)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum score to be considered compliant (0-100)', max_digits=6, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_programs', to='api.businessunit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_compliance_programs',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('non_compliant', 'Non-Compliant'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_compliant', models.BooleanField(default=False)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assignments', to='api.company')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.complianceprogram')),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='api.complianceassignment')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_assignments', to='api.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_compliance_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('initial', 'Initial Compliance'), ('renewal', 'Renewal'), ('audit', 'Audit'), ('override', 'Manual Override')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.complianceassignment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reviews', to='api.company')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.complianceprogram')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_compliance_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_compliance_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'user'], name='enterprise__company_52d46a_idx'), models.Index(fields=['company', 'program'], name='enterprise__company_7db0ab_idx'), models.Index(fields=['user', 'program'], name='enterprise__user_id_49176d_idx'), models.Index(fields=['company', 'status'], name='enterprise__company_a275d8_idx'), models.Index(fields=['created_at'], name='enterprise__created_76f181_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_requirements', to='api.learningpath')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.complianceprogram')),
            ],
            options={
                'db_table': 'enterprise_compliance_requirements',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['program', 'order'], name='enterprise__program_e2c7f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complianceprogram',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_7d1ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceprogram',
            index=models.Index(fields=['company', 'compliance_type'], name='enterprise__company_97b9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceprogram',
            index=models.Index(fields=['company', 'is_mandatory'], name='enterprise__company_e6209c_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceprogram',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_compliance_program_company_code'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['company', 'status'], name='enterprise__company_56d266_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['company', 'program'], name='enterprise__company_e170ca_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['user', 'status'], name='enterprise__user_id_67d22d_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['team', 'status'], name='enterprise__team_id_1435de_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['company', 'user', 'status'], name='enterprise__company_fd7670_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['expires_at'], name='enterprise__expires_92e86d_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassignment',
            index=models.Index(fields=['due_date'], name='enterprise__due_dat_1f54b1_idx'),
        ),
    ]
