# Generated by Django 4.2.27 on 2026-06-25 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_enterprise_phase4_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique code within the company', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('course_completion', 'Course Completion'), ('compliance', 'Compliance'), ('skill_mastery', 'Skill Mastery'), ('certification', 'Professional Certification'), ('custom', 'Custom')], default='course_completion', max_length=30)),
                ('header_text', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('requires_score', models.BooleanField(default=False)),
                ('minimum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('validity_days', models.PositiveIntegerField(default=0, help_text='Days the certificate is valid (0 = no expiry)')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='CertificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('minimum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_requirements', to='api.complianceprogram')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_requirements', to='api.learningpath')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.certificatetemplate')),
            ],
            options={
                'db_table': 'enterprise_certification_requirements',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['template', 'order'], name='enterprise__templat_ec6fb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_code', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='api.company')),
                ('compliance_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='api.complianceprogram')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certifications', to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='api.learningpath')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certifications', to='api.certificatetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_certifications',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['company', 'user'], name='enterprise__company_1fb2e0_idx'), models.Index(fields=['company', 'status'], name='enterprise__company_b4fb58_idx'), models.Index(fields=['company', 'template'], name='enterprise__company_164c8d_idx'), models.Index(fields=['user', 'status'], name='enterprise__user_id_8ca751_idx'), models.Index(fields=['expires_at'], name='enterprise__expires_147172_idx'), models.Index(fields=['issued_at'], name='enterprise__issued__954140_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['company', 'template_type'], name='enterprise__company_3eadf0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['company', 'is_active'], name='enterprise__company_f1bf95_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_certificate_template_company_code'),
        ),
    ]
