# Generated by Django 4.2.27 on 2026-06-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_assignment_supports_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('assignment_notification', 'Assignment Notification'), ('added_to_company', 'Added to Company'), ('added_to_team', 'Added to Team'), ('added_to_business_unit', 'Added to Business Unit'), ('reminder', 'Reminder')], max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('body_preview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enterprise_email_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='changeimpactanalysis',
            new_name='enterprise__company_508d7a_idx',
            old_name='ent_cia_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='changeimpactanalysis',
            new_name='enterprise__company_1000df_idx',
            old_name='ent_cia_company_impact_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgenode',
            new_name='enterprise__company_359f9a_idx',
            old_name='ent_kn_company_type_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgenode',
            new_name='enterprise__company_b337bc_idx',
            old_name='ent_kn_company_score_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgesource',
            new_name='enterprise__company_4c0b51_idx',
            old_name='ent_ks_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgesource',
            new_name='enterprise__company_f2ac65_idx',
            old_name='ent_ks_company_type_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmodule',
            new_name='enterprise__company_0cd08a_idx',
            old_name='enterprise_lm_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='procedure',
            new_name='enterprise__company_a8fd66_idx',
            old_name='ent_proc_company_ks_idx',
        ),
        migrations.RenameIndex(
            model_name='procedure',
            new_name='enterprise__company_8c453c_idx',
            old_name='ent_proc_company_critical_idx',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='api.company'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['company', 'email_type'], name='enterprise__company_60e888_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email'], name='enterprise__recipie_820728_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sent_at'], name='enterprise__sent_at_3df288_idx'),
        ),
    ]
