# Generated by Django 4.2.27 on 2026-06-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_email_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('general', 'General'), ('study', 'Study'), ('enterprise', 'Enterprise'), ('batch', 'Batch')], default='general', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_groups', to='api.collection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deck',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='GenerationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_type', models.CharField(choices=[('assessment', 'Assessment'), ('flashcards', 'Flashcards'), ('generic', 'Generic')], default='assessment', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_profiles', to='api.collection')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='api.collection'),
        ),
        migrations.AddField(
            model_name='battery',
            name='generation_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='api.generationprofile'),
        ),
        migrations.AddField(
            model_name='deck',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='api.collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.collection'),
        ),
        migrations.CreateModel(
            name='TagGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.taggroup')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('tag_group', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DeckSourceTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tag_groups', to='api.deck')),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_sources', to='api.taggroup')),
            ],
            options={
                'unique_together': {('deck', 'tag_group', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DeckSourceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sections', to='api.deck')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_sources', to='api.section')),
            ],
            options={
                'unique_together': {('deck', 'section', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DeckSourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='api.deck')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_sources', to='api.document')),
            ],
            options={
                'unique_together': {('deck', 'document', 'role')},
            },
        ),
        migrations.CreateModel(
            name='BatterySourceTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tag_groups', to='api.battery')),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_sources', to='api.taggroup')),
            ],
            options={
                'unique_together': {('battery', 'tag_group', 'role')},
            },
        ),
        migrations.CreateModel(
            name='BatterySourceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sections', to='api.battery')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_sources', to='api.section')),
            ],
            options={
                'unique_together': {('battery', 'section', 'role')},
            },
        ),
        migrations.CreateModel(
            name='BatterySourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='input', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='api.battery')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery_sources', to='api.document')),
            ],
            options={
                'unique_together': {('battery', 'document', 'role')},
            },
        ),
    ]
