# Generated by Django 4.2.27 on 2026-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_phase1_generic_collections'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='uniq_document_project_hash',
        ),
        migrations.AlterField(
            model_name='battery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='api.project'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='api.project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.project'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.project'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='api.project'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('collection', 'hash'), name='uniq_document_collection_hash'),
        ),
    ]
