# Generated by Django 4.2.27 on 2026-06-28 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_process_first_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_key', models.CharField(db_index=True, max_length=120)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('event', 'Event'), ('schedule', 'Schedule'), ('retry', 'Retry'), ('system', 'System')], default='manual', max_length=20)),
                ('scope_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('scope_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('resource_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('current_step_key', models.CharField(blank=True, default='', max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'process_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStepRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_key', models.CharField(db_index=True, max_length=120)),
                ('item_key', models.CharField(blank=True, default='', max_length=120)),
                ('step_type', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('execution_mode', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('batch', 'Batch'), ('fanout', 'Fan-out'), ('join', 'Join')], default='async', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('external_job_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_payload', models.JSONField(blank=True, default=dict)),
                ('runtime_metrics', models.JSONField(blank=True, default=dict)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.processrun')),
            ],
            options={
                'db_table': 'process_step_runs',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStepDependency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dependency_kind', models.CharField(choices=[('requires', 'Requires'), ('soft_requires', 'Soft requires'), ('blocks', 'Blocks'), ('joins', 'Joins')], default='requires', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='api.processsteprun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='api.processsteprun')),
            ],
            options={
                'db_table': 'process_step_dependencies',
            },
        ),
        migrations.CreateModel(
            name='ProcessArtifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artifact_key', models.CharField(max_length=120)),
                ('artifact_type', models.CharField(db_index=True, max_length=80)),
                ('role', models.CharField(choices=[('input', 'Input'), ('intermediate', 'Intermediate'), ('output', 'Output'), ('reference', 'Reference')], default='output', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('resource_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('produced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.processrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='api.processsteprun')),
            ],
            options={
                'db_table': 'process_artifacts',
            },
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['run', 'status'], name='process_ste_run_id_2e3c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['step_key', 'status'], name='process_ste_step_ke_efaf15_idx'),
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['external_job_id'], name='process_ste_externa_708a84_idx'),
        ),
        migrations.AddIndex(
            model_name='processsteprun',
            index=models.Index(fields=['idempotency_key'], name='process_ste_idempot_43aa66_idx'),
        ),
        migrations.AddConstraint(
            model_name='processsteprun',
            constraint=models.UniqueConstraint(fields=('run', 'step_key', 'item_key'), name='uniq_process_step_run_key'),
        ),
        migrations.AddIndex(
            model_name='processstepdependency',
            index=models.Index(fields=['step', 'dependency_kind'], name='process_ste_step_id_a440b6_idx'),
        ),
        migrations.AddIndex(
            model_name='processstepdependency',
            index=models.Index(fields=['depends_on', 'dependency_kind'], name='process_ste_depends_b9d617_idx'),
        ),
        migrations.AddConstraint(
            model_name='processstepdependency',
            constraint=models.UniqueConstraint(fields=('step', 'depends_on', 'dependency_kind'), name='uniq_process_step_dependency'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['workflow_key', 'status'], name='process_run_workflo_a25d45_idx'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['resource_type', 'resource_id'], name='process_run_resourc_edd17d_idx'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['scope_type', 'scope_id'], name='process_run_scope_t_0ade5d_idx'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['job_id'], name='process_run_job_id_c0312f_idx'),
        ),
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['idempotency_key'], name='process_run_idempot_8a1b44_idx'),
        ),
        migrations.AddIndex(
            model_name='processartifact',
            index=models.Index(fields=['artifact_type', 'status'], name='process_art_artifac_487e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='processartifact',
            index=models.Index(fields=['resource_type', 'resource_id'], name='process_art_resourc_bc541f_idx'),
        ),
        migrations.AddIndex(
            model_name='processartifact',
            index=models.Index(fields=['fingerprint'], name='process_art_fingerp_8668bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='processartifact',
            constraint=models.UniqueConstraint(fields=('run', 'artifact_key'), name='uniq_process_artifact_key'),
        ),
    ]
