# Generated by Django 4.2.27 on 2026-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_processrun_processsteprun_processstepdependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='control_state',
            field=models.CharField(choices=[('active', 'Active'), ('pause_requested', 'Pause requested'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='processrun',
            name='current_stage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='processrun',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='pause_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processrun',
            name='pause_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='processrun',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='checkpoint_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='checkpoint_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='control_state',
            field=models.CharField(choices=[('active', 'Active'), ('pause_requested', 'Pause requested'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='pause_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processsteprun',
            name='worker_step',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='processsteprun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
    ]
