# Generated by Django 4.2.27 on 2026-07-05 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_knowledgesourcedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('trainer', 'Trainer'), ('employee', 'Employee'), ('auditor', 'Auditor')], default='employee', max_length=20)),
                ('employee_stage', models.CharField(choices=[('candidate', 'Candidate'), ('onboarding', 'Onboarding'), ('trainee', 'Trainee'), ('active_employee', 'Active Employee'), ('contractor', 'Contractor'), ('former_employee', 'Former Employee')], default='onboarding', max_length=30)),
                ('token', models.UUIDField(db_index=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enterprise_company_invitations',
                'indexes': [models.Index(fields=['company', 'status'], name='enterprise__company_60c0ed_idx'), models.Index(fields=['email', 'status'], name='enterprise__email_2b7482_idx'), models.Index(fields=['token'], name='enterprise__token_55de30_idx'), models.Index(fields=['expires_at'], name='enterprise__expires_8a0902_idx')],
            },
        ),
    ]
