# Generated by Django 4.2.27 on 2026-07-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_company_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
