# Generated by Django 4.2.27 on 2026-07-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_battery_order_deck_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='knowledge_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_modules', to='api.knowledgesource'),
        ),
    ]
