# Generated by Django 4.2.27 on 2026-07-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_learningmodule_knowledge_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('assignment_notification', 'Assignment Notification'), ('compliance_assignment_notification', 'Compliance Assignment Notification'), ('added_to_company', 'Added to Company'), ('added_to_team', 'Added to Team'), ('added_to_business_unit', 'Added to Business Unit'), ('reminder', 'Reminder')], max_length=40),
        ),
    ]
